/** Full ISO 4217 active-currency list — 131 entries.
 *
 *  Decimal precision follows the official ISO minor-unit exponent: 0 for
 *  currencies with no subdivision in practice, 3 for the Gulf dinar/rial
 *  currencies, 2 otherwise. Copied verbatim from the v1 implementation;
 *  the tuple shape is [code, symbol, name, decimals?].
 */
type CurrencyRow = readonly [code: string, symbol: string, name: string, decimals?: number];

export const CURRENCIES: readonly CurrencyRow[] = [
  ["INR", "\u20B9", "Indian Rupee"],
  ["USD", "$", "US Dollar"],
  ["EUR", "\u20AC", "Euro"],
  ["GBP", "\u00A3", "British Pound"],
  ["AED", "AED ", "UAE Dirham"],
  ["SAR", "SAR ", "Saudi Riyal"],
  ["QAR", "QAR ", "Qatari Riyal"],
  ["KWD", "KWD ", "Kuwaiti Dinar", 3],
  ["BHD", "BHD ", "Bahraini Dinar", 3],
  ["OMR", "OMR ", "Omani Rial", 3],
  ["JOD", "JOD ", "Jordanian Dinar", 3],
  ["IQD", "IQD ", "Iraqi Dinar", 3],
  ["LYD", "LYD ", "Libyan Dinar", 3],
  ["TND", "TND ", "Tunisian Dinar", 3],
  ["NOK", "kr ", "Norwegian Krone"],
  ["SEK", "kr ", "Swedish Krona"],
  ["DKK", "kr ", "Danish Krone"],
  ["ISK", "kr ", "Icelandic Krona", 0],
  ["CHF", "CHF ", "Swiss Franc"],
  ["SGD", "S$", "Singapore Dollar"],
  ["AUD", "A$", "Australian Dollar"],
  ["NZD", "NZ$", "New Zealand Dollar"],
  ["CAD", "C$", "Canadian Dollar"],
  ["HKD", "HK$", "Hong Kong Dollar"],
  ["JPY", "\u00A5", "Japanese Yen", 0],
  ["CNY", "\u00A5", "Chinese Yuan"],
  ["MYR", "RM", "Malaysian Ringgit"],
  ["THB", "\u0E3F", "Thai Baht"],
  ["IDR", "Rp", "Indonesian Rupiah", 0],
  ["PHP", "\u20B1", "Philippine Peso"],
  ["VND", "\u20AB", "Vietnamese Dong", 0],
  ["ZAR", "R", "South African Rand"],
  ["EGP", "E\u00A3", "Egyptian Pound"],
  ["NGN", "\u20A6", "Nigerian Naira"],
  ["KES", "KSh", "Kenyan Shilling"],
  ["GHS", "GH\u20B5", "Ghanaian Cedi"],
  ["TZS", "TSh", "Tanzanian Shilling"],
  ["UGX", "USh", "Ugandan Shilling", 0],
  ["RWF", "RF", "Rwandan Franc", 0],
  ["ZMW", "ZK", "Zambian Kwacha"],
  ["MAD", "MAD ", "Moroccan Dirham"],
  ["DZD", "DZD ", "Algerian Dinar"],
  ["ETB", "Br", "Ethiopian Birr"],
  ["XOF", "CFA", "West African CFA Franc", 0],
  ["XAF", "FCFA", "Central African CFA Franc", 0],
  ["XPF", "CFP", "CFP Franc", 0],
  ["MUR", "\u20A8", "Mauritian Rupee"],
  ["BWP", "P", "Botswana Pula"],
  ["NAD", "N$", "Namibian Dollar"],
  ["PKR", "\u20A8", "Pakistani Rupee"],
  ["BDT", "\u09F3", "Bangladeshi Taka"],
  ["LKR", "Rs", "Sri Lankan Rupee"],
  ["NPR", "Rs", "Nepalese Rupee"],
  ["AFN", "\u060B", "Afghan Afghani"],
  ["MMK", "K", "Myanmar Kyat"],
  ["KHR", "\u17DB", "Cambodian Riel"],
  ["LAK", "\u20AD", "Lao Kip"],
  ["MNT", "\u20AE", "Mongolian Tugrik"],
  ["KZT", "\u20B8", "Kazakhstani Tenge"],
  ["UZS", "so'm", "Uzbekistani Som"],
  ["AZN", "\u20BC", "Azerbaijani Manat"],
  ["GEL", "\u20BE", "Georgian Lari"],
  ["AMD", "\u058F", "Armenian Dram"],
  ["RUB", "\u20BD", "Russian Ruble"],
  ["UAH", "\u20B4", "Ukrainian Hryvnia"],
  ["BYN", "Br", "Belarusian Ruble"],
  ["TRY", "\u20BA", "Turkish Lira"],
  ["ILS", "\u20AA", "Israeli Shekel"],
  ["LBP", "LBP ", "Lebanese Pound"],
  ["JMD", "J$", "Jamaican Dollar"],
  ["TTD", "TT$", "Trinidad and Tobago Dollar"],
  ["BSD", "B$", "Bahamian Dollar"],
  ["BBD", "Bds$", "Barbadian Dollar"],
  ["BZD", "BZ$", "Belize Dollar"],
  ["XCD", "EC$", "East Caribbean Dollar"],
  ["GYD", "G$", "Guyanese Dollar"],
  ["SRD", "SRD ", "Surinamese Dollar"],
  ["CUP", "CUP ", "Cuban Peso"],
  ["DOP", "RD$", "Dominican Peso"],
  ["HTG", "G", "Haitian Gourde"],
  ["GTQ", "Q", "Guatemalan Quetzal"],
  ["HNL", "L", "Honduran Lempira"],
  ["NIO", "C$", "Nicaraguan Cordoba"],
  ["CRC", "\u20A1", "Costa Rican Colon"],
  ["PAB", "B/.", "Panamanian Balboa"],
  ["MXN", "MX$", "Mexican Peso"],
  ["BRL", "R$", "Brazilian Real"],
  ["ARS", "AR$", "Argentine Peso"],
  ["CLP", "CL$", "Chilean Peso", 0],
  ["COP", "COL$", "Colombian Peso"],
  ["PEN", "S/", "Peruvian Sol"],
  ["BOB", "Bs.", "Bolivian Boliviano"],
  ["PYG", "\u20B2", "Paraguayan Guarani", 0],
  ["UYU", "$U", "Uruguayan Peso"],
  ["VES", "Bs.S", "Venezuelan Bolivar"],
  ["PLN", "z\u0142", "Polish Zloty"],
  ["CZK", "K\u010D", "Czech Koruna"],
  ["HUF", "Ft", "Hungarian Forint"],
  ["RON", "lei", "Romanian Leu"],
  ["BGN", "\u043B\u0432", "Bulgarian Lev"],
  ["RSD", "din.", "Serbian Dinar"],
  ["ALL", "L", "Albanian Lek"],
  ["MKD", "\u0434\u0435\u043D", "Macedonian Denar"],
  ["BAM", "KM", "Bosnia-Herzegovina Mark"],
  ["MDL", "L", "Moldovan Leu"],
  ["KRW", "\u20A9", "South Korean Won", 0],
  ["KPW", "\u20A9", "North Korean Won"],
  ["TWD", "NT$", "Taiwan Dollar"],
  ["MOP", "MOP$", "Macanese Pataca"],
  ["FJD", "FJ$", "Fijian Dollar"],
  ["PGK", "K", "Papua New Guinean Kina"],
  ["WST", "WS$", "Samoan Tala"],
  ["TOP", "T$", "Tongan Pa'anga"],
  ["SBD", "SI$", "Solomon Islands Dollar"],
  ["VUV", "VT", "Vanuatu Vatu", 0],
  ["YER", "YER ", "Yemeni Rial"],
  ["SYP", "SYP ", "Syrian Pound"],
  ["IRR", "IRR ", "Iranian Rial"],
  ["SDG", "SDG ", "Sudanese Pound"],
  ["SSP", "SSP ", "South Sudanese Pound"],
  ["SOS", "S", "Somali Shilling"],
  ["DJF", "Fdj", "Djiboutian Franc", 0],
  ["ERN", "Nfk", "Eritrean Nakfa"],
  ["KMF", "CF", "Comorian Franc", 0],
  ["MGA", "Ar", "Malagasy Ariary", 0],
  ["MWK", "MK", "Malawian Kwacha"],
  ["MZN", "MT", "Mozambican Metical"],
  ["ZWL", "Z$", "Zimbabwean Dollar"],
  ["AOA", "Kz", "Angolan Kwanza"],
  ["CDF", "FC", "Congolese Franc"],
  ["XDR", "SDR", "IMF Special Drawing Rights"],
];

export interface Currency {
  code: string;
  symbol: string;
  name: string;
  decimals: number;
}

const FALLBACK: Currency = { code: "INR", symbol: "₹", name: "Indian Rupee", decimals: 2 };

/** Unknown codes fall back to INR — v1 behaviour, and the safe default for
 *  legacy records written before the currency field existed. */
export function getCurrency(code: string | null | undefined): Currency {
  const found = CURRENCIES.find((c) => c[0] === code);
  if (!found) return FALLBACK;
  return { code: found[0], symbol: found[1], name: found[2], decimals: found[3] ?? 2 };
}
