/**
 * The currency a customer in each country is most likely to be invoiced in.
 *
 * WHY THIS HAD TO EXIST. A customer outside India was saved with no currency
 * at all, and normalisation then filled the blank with INR — the default
 * that is right for almost every record in this CRM and wrong for exactly
 * the ones this map is about. A quotation to Dubai came out priced in
 * rupees. Nobody had to make a mistake for that to happen; it was what the
 * software did on its own.
 *
 * IT IS A STARTING POINT, NEVER A RULE. Plenty of Gulf business is quoted in
 * dollars and plenty of European business in euros whatever the customer's
 * own currency is, so this only ever pre-fills a field somebody can change,
 * and changing it is never overridden afterwards.
 *
 * WHERE A COUNTRY'S OWN CURRENCY IS NOT ONE THIS CRM CAN RENDER, the entry
 * names one that is actually used there rather than inventing a symbol and a
 * rounding rule: Bhutan bills in rupees, Brunei accepts Singapore dollars at
 * par, Lesotho and Eswatini take rand. Where nothing sensible applies the
 * answer is the dollar, which is what cross-border trade defaults to anyway.
 *
 * MIRRORED IN netlify/lib/currencyForCountry.mjs, which the registration
 * form's server uses, and pinned to it by a parity test. Change one, change
 * both, and the test will say so if you do not.
 */

export const CURRENCY_BY_COUNTRY: Readonly<Record<string, string>> = {
  "Afghanistan":                         "AFN",
  "Albania":                             "ALL",
  "Algeria":                             "DZD",
  "Andorra":                             "EUR",
  "Angola":                              "AOA",
  "Antigua and Barbuda":                 "XCD",
  "Argentina":                           "ARS",
  "Armenia":                             "AMD",
  "Australia":                           "AUD",
  "Austria":                             "EUR",
  "Azerbaijan":                          "AZN",
  "Bahamas":                             "BSD",
  "Bahrain":                             "BHD",
  "Bangladesh":                          "BDT",
  "Barbados":                            "BBD",
  "Belarus":                             "BYN",
  "Belgium":                             "EUR",
  "Belize":                              "BZD",
  "Benin":                               "XOF",
  "Bhutan":                              "INR",
  "Bolivia":                             "BOB",
  "Bosnia and Herzegovina":              "BAM",
  "Botswana":                            "BWP",
  "Brazil":                              "BRL",
  "Brunei":                              "SGD",
  "Bulgaria":                            "BGN",
  "Burkina Faso":                        "XOF",
  "Burundi":                             "USD",
  "Cambodia":                            "KHR",
  "Cameroon":                            "XAF",
  "Canada":                              "CAD",
  "Cape Verde":                          "EUR",
  "Central African Republic":            "XAF",
  "Chad":                                "XAF",
  "Chile":                               "CLP",
  "China":                               "CNY",
  "Colombia":                            "COP",
  "Comoros":                             "KMF",
  "Congo (Brazzaville)":                 "XAF",
  "Congo (DRC)":                         "CDF",
  "Costa Rica":                          "CRC",
  "Croatia":                             "EUR",
  "Cuba":                                "CUP",
  "Cyprus":                              "EUR",
  "Czech Republic":                      "CZK",
  "Denmark":                             "DKK",
  "Djibouti":                            "DJF",
  "Dominica":                            "XCD",
  "Dominican Republic":                  "DOP",
  "East Timor":                          "USD",
  "Ecuador":                             "USD",
  "Egypt":                               "EGP",
  "El Salvador":                         "USD",
  "Equatorial Guinea":                   "XAF",
  "Eritrea":                             "ERN",
  "Estonia":                             "EUR",
  "Eswatini":                            "ZAR",
  "Ethiopia":                            "ETB",
  "Fiji":                                "FJD",
  "Finland":                             "EUR",
  "France":                              "EUR",
  "Gabon":                               "XAF",
  "Gambia":                              "USD",
  "Georgia":                             "GEL",
  "Germany":                             "EUR",
  "Ghana":                               "GHS",
  "Greece":                              "EUR",
  "Grenada":                             "XCD",
  "Guatemala":                           "GTQ",
  "Guinea":                              "USD",
  "Guinea-Bissau":                       "XOF",
  "Guyana":                              "GYD",
  "Haiti":                               "HTG",
  "Honduras":                            "HNL",
  "Hong Kong":                           "HKD",
  "Hungary":                             "HUF",
  "Iceland":                             "ISK",
  "India":                               "INR",
  "Indonesia":                           "IDR",
  "Iran":                                "IRR",
  "Iraq":                                "IQD",
  "Ireland":                             "EUR",
  "Israel":                              "ILS",
  "Italy":                               "EUR",
  "Ivory Coast":                         "XOF",
  "Jamaica":                             "JMD",
  "Japan":                               "JPY",
  "Jordan":                              "JOD",
  "Kazakhstan":                          "KZT",
  "Kenya":                               "KES",
  "Kiribati":                            "AUD",
  "Kosovo":                              "EUR",
  "Kuwait":                              "KWD",
  "Kyrgyzstan":                          "USD",
  "Laos":                                "LAK",
  "Latvia":                              "EUR",
  "Lebanon":                             "LBP",
  "Lesotho":                             "ZAR",
  "Liberia":                             "USD",
  "Libya":                               "LYD",
  "Liechtenstein":                       "CHF",
  "Lithuania":                           "EUR",
  "Luxembourg":                          "EUR",
  "Macau":                               "MOP",
  "Madagascar":                          "MGA",
  "Malawi":                              "MWK",
  "Malaysia":                            "MYR",
  "Maldives":                            "USD",
  "Mali":                                "XOF",
  "Malta":                               "EUR",
  "Marshall Islands":                    "USD",
  "Mauritania":                          "USD",
  "Mauritius":                           "MUR",
  "Mexico":                              "MXN",
  "Micronesia":                          "USD",
  "Moldova":                             "MDL",
  "Monaco":                              "EUR",
  "Mongolia":                            "MNT",
  "Montenegro":                          "EUR",
  "Morocco":                             "MAD",
  "Mozambique":                          "MZN",
  "Myanmar":                             "MMK",
  "Namibia":                             "NAD",
  "Nauru":                               "AUD",
  "Nepal":                               "NPR",
  "Netherlands":                         "EUR",
  "New Zealand":                         "NZD",
  "Nicaragua":                           "NIO",
  "Niger":                               "XOF",
  "Nigeria":                             "NGN",
  "North Korea":                         "KPW",
  "North Macedonia":                     "MKD",
  "Norway":                              "NOK",
  "Oman":                                "OMR",
  "Pakistan":                            "PKR",
  "Palau":                               "USD",
  "Palestine":                           "ILS",
  "Panama":                              "PAB",
  "Papua New Guinea":                    "PGK",
  "Paraguay":                            "PYG",
  "Peru":                                "PEN",
  "Philippines":                         "PHP",
  "Poland":                              "PLN",
  "Portugal":                            "EUR",
  "Puerto Rico":                         "USD",
  "Qatar":                               "QAR",
  "Romania":                             "RON",
  "Russia":                              "RUB",
  "Rwanda":                              "RWF",
  "Saint Kitts and Nevis":               "XCD",
  "Saint Lucia":                         "XCD",
  "Saint Vincent and the Grenadines":    "XCD",
  "Samoa":                               "WST",
  "San Marino":                          "EUR",
  "Sao Tome and Principe":               "USD",
  "Saudi Arabia":                        "SAR",
  "Senegal":                             "XOF",
  "Serbia":                              "RSD",
  "Seychelles":                          "USD",
  "Sierra Leone":                        "USD",
  "Singapore":                           "SGD",
  "Slovakia":                            "EUR",
  "Slovenia":                            "EUR",
  "Solomon Islands":                     "SBD",
  "Somalia":                             "SOS",
  "South Africa":                        "ZAR",
  "South Korea":                         "KRW",
  "South Sudan":                         "SSP",
  "Spain":                               "EUR",
  "Sri Lanka":                           "LKR",
  "Sudan":                               "SDG",
  "Suriname":                            "SRD",
  "Sweden":                              "SEK",
  "Switzerland":                         "CHF",
  "Syria":                               "SYP",
  "Taiwan":                              "TWD",
  "Tajikistan":                          "USD",
  "Tanzania":                            "TZS",
  "Thailand":                            "THB",
  "Togo":                                "XOF",
  "Tonga":                               "TOP",
  "Trinidad and Tobago":                 "TTD",
  "Tunisia":                             "TND",
  "Turkey":                              "TRY",
  "Turkmenistan":                        "USD",
  "Tuvalu":                              "AUD",
  "Uganda":                              "UGX",
  "Ukraine":                             "UAH",
  "United Arab Emirates":                "AED",
  "United Kingdom":                      "GBP",
  "United States":                       "USD",
  "Uruguay":                             "UYU",
  "Uzbekistan":                          "UZS",
  "Vanuatu":                             "VUV",
  "Vatican City":                        "EUR",
  "Venezuela":                           "VES",
  "Vietnam":                             "VND",
  "Yemen":                               "YER",
  "Zambia":                              "ZMW",
  "Zimbabwe":                            "ZWL",
};

/** What cross-border trade falls back to when the country is unknown, blank,
 *  or "Other". Not a guess about that country — an admission that there is
 *  nothing to go on, and the dollar is what people then use. */
export const DEFAULT_INTERNATIONAL_CURRENCY = "USD";

export function currencyForCountry(country: string | null | undefined): string {
  const name = String(country ?? "").trim();
  if (!name) return DEFAULT_INTERNATIONAL_CURRENCY;
  return CURRENCY_BY_COUNTRY[name] ?? DEFAULT_INTERNATIONAL_CURRENCY;
}
